<?php

namespace GitHubApi;

// This file is generated by Composer
require_once 'vendor/autoload.php';


class GitHubApi
{
    /**
     * get repository data from GitHub client
     * @return array
     * @throws \Exception When connection error occur
     */
    public function getGitHubApiData()
    {
        try {

            $client = new \Github\Client();
            $response = $client->api('repo')->find('symfony');
            return $response['repositories'];

        } catch (\Exception $e) {
            echo $e->getMessage();
        }
    }
}